### ISSUE TITLE
edumfa-manage policy create -f optional argument error

### ISSUE THREAD

**Issue by MarcZiegler** [eduMFA/eduMFA#153]
### Top-level intent

Generate a policy using edumfa-manage from a file

### Steps to reproduce

Call "edumfa-manage policy create -f file.ini default default default" where file.ini is a config file for a policy according to specifications

### Expected outcome

The command should accept the argument -f and generate the policy

### Actual outcome

received error "TypeError: create() got an unexpected keyword argument 'f'" and no policy was created

### Configuration

* **eduMFA version**:  2.0?
* **Installation method**: compiled from main
* **Python version**: 3.12.3
* **Operating system**: docker container with python:3.12-slim-bookworm
* **Webserver**: Gunicorn
* **Token database**: MariaDB

### Custom solution so far
In _edumfa\commands\manage\policy.py_ changed definition and mentions of `filename` to `f`

e.g.
`def create(name, scope, action, filename):`
to 
`def create(name, scope, action, f):`

**Comment by fritterhoff** [comment]
Hi! 

Thanks for the bug report. Seems like that really broke during the refactoring action. Will fix that.
