### ISSUE TITLE
Web UI - Field for entering the MFA token

### ISSUE THREAD

**Issue by zimttat** [eduMFA/eduMFA#163]
**Is your feature request related to a problem? Please describe.**

User interfase in the Web UI needs a separate field for entering the MFA token. That is a usabilty problem. Enter the TOTP behind the password into Password field is unusual and is reason for user mistakes.

**Describe the solution you'd like**

Implementation a separated field for totp token.

**Describe alternatives you've considered**

Add any other context or screenshots, that might help us to better understand your idea, your need and your circumstances.

For eduMFA developers. Describe and document the development plans:

![git](https://github.com/eduMFA/eduMFA/assets/79644288/3fda401d-cddf-4d27-b40a-931e992da4ab)
# Top level requirements and scenarios

*Describe what needs to be achieved and how the scenario looks like*

*If sensible use a checklist to check, which requirements have been covered by your implementation!*

* [ ] We need to ensure that...
* [ ] Administrators must be able to...

# Implementation

*Describe your implementation plans - what you are exactly going to implement. Use references/link to the existing code*

*Cover the following aspects:*

## Database

Describe the database table that will be added. Define the `name` of the table and the `names of the columns`.

Define, if you need to add a DB migration script.

## Library and API

Describe what needs to be implemented, preferably also in which files.

Use example code of what you plan to implement:

~~~~Python
new_feature = [ x.name for x in some_return_values if x.id > 0 ]
~~~~

# TODOs

*In the TODO section you can add all steps that need to be implemented*

**USE CHECKLISTS, THESE WILL BE VISIBLE AS TASKS!**

* [ ] add DB table `name` in `models.py`
* [ ] create above mentioned migration script.
* ~~[ ] there might be an aspect that is not relevant anymore~~
* [ ] e.g. Add util function to...
* [ ] e.g. add REST API...
* [ ] e.g. we need to add policy and implement it in e.g. `prepolicy`
  - scope: admin
  - action: new_action_name
  - ...    

Use further checkboxes for

* [ ] add documentation
* [ ] implement tests

**Comment by fritterhoff** [comment]
Hi! Thanks for the idea. We will discuss that in our team the next few days. 

At this point in time, however, I cannot estimate whether we will implement this feature (in the near future), as our focus is on the APIs.

**Comment by pmainz** [comment]
We have discussed the issue. Although the demand for such a second input field is reasonable we will not implement that in the near future because as @fritterhoff already pointed out we focus on the APIs.
There is however the opportunity to use the already implemented second field which exists for challenge response token. If you use challenge response token for authentication to the webUI a second input field will appear after entering username and password/pin. In order to make this work for TOTP which is not a native challenge response token, you just need to add an authentication policy to tell eduMFA to treat it like one. The relevant policy setting is called 'challenge_response' in the policy scope 'authentication':
https://edumfa.readthedocs.io/en/v2.0.2/policies/authentication.html#challenge-response

**Comment by j-hoff** [comment]
I think the solution @pmainz described is the way to go.
At the moment I do not see a reason for an additional field in the login view.

**Comment by Woo6vop7** [comment]
> We have discussed the issue. Although the demand for such a second input field is reasonable we will not implement that in the near future because as [@fritterhoff](https://github.com/fritterhoff) already pointed out we focus on the APIs. There is however the opportunity to use the already implemented second field which exists for challenge response token. If you use challenge response token for authentication to the webUI a second input field will appear after entering username and password/pin. In order to make this work for TOTP which is not a native challenge response token, you just need to add an authentication policy to tell eduMFA to treat it like one. The relevant policy setting is called 'challenge_response' in the policy scope 'authentication': https://edumfa.readthedocs.io/en/v2.0.2/policies/authentication.html#challenge-response

I have tried this solution, but unfortunately, after logging in via Username + Password (userstore), there is no prompt for the second factor, despite setting `totp` in the `challenge response` option and a second token already issued to the user. `otppin=userstore` is set, but doesn't change the outcome.

Edit: It does work, but is completely unintuitive and not documented at all. That seems pretty strange for a feature, that would be desirable from a security standpoint.
