### ISSUE TITLE
Have a token desription/name and creation date in the list

### ISSUE THREAD

**Issue by ghost** [eduMFA/eduMFA#180]
**Is your feature request related to a problem? Please describe.**

Problem: If a user sees multiple MFA tokens in their list, it is hard to tell which is which. This can be a problem if, for instance, they have two different tokens on two different devices and one of them gets lost. They now want to invalidate the token stored on the lost device (meaning delete it in eduMFA), but in order to do that, they must know which token that is.

**Describe the solution you'd like**

Proposed solution: store a user-supplied name (like, e.g. "on my work iPad") and the creation date with each token and show these in the list of tokens. This akin to GitLab showing the user, among other things, a token name and a creation date in their list of access tokens, so they can clearly distinguish different tokens.

**Describe alternatives you've considered**

None.

**Additional context**

Screenshot from Gitlab:

<img width="1061" alt="Screenshot 2024-06-10 at 16 26 26" src="https://github.com/eduMFA/eduMFA/assets/11918910/a7eb0bbf-8771-46a1-a374-f461e50b4c68">

For eduMFA developers. Describe and document the development plans:

# Top level requirements and scenarios

*Describe what needs to be achieved and how the scenario looks like*

*If sensible use a checklist to check, which requirements have been covered by your implementation!*

* [ ] We need to ensure that...
* [ ] Administrators must be able to...

# Implementation

*Describe your implementation plans - what you are exactly going to implement. Use references/link to the existing code*

*Cover the following aspects:*

## Database

Describe the database table that will be added. Define the `name` of the table and the `names of the columns`.

Define, if you need to add a DB migration script.

## Library and API

Describe what needs to be implemented, preferably also in which files.

Use example code of what you plan to implement:

~~~~Python
new_feature = [ x.name for x in some_return_values if x.id > 0 ]
~~~~

# TODOs

*In the TODO section you can add all steps that need to be implemented*

**USE CHECKLISTS, THESE WILL BE VISIBLE AS TASKS!**

* [ ] add DB table `name` in `models.py`
* [ ] create above mentioned migration script.
* ~~[ ] there might be an aspect that is not relevant anymore~~
* [ ] e.g. Add util function to...
* [ ] e.g. add REST API...
* [ ] e.g. we need to add policy and implement it in e.g. `prepolicy`
  - scope: admin
  - action: new_action_name
  - ...    

Use further checkboxes for

* [ ] add documentation
* [ ] implement tests

**Comment by j-hoff** [comment]
Hi Jürgen,
we use the token **description** for this purpose. Could this work in your case as well?

**Comment by ghost** [comment]
That does indeed sound like what I want. I must admit I am not the developer working with eduMFA, but a colleague of mine is, and he said there is no such thing. Now he may have been in error; I think I'll have to prod him again.

Additionally, a creation date would be a very welcome addition, but not as important as a description. With that, I can live. Thanks!
(und Hallo, Jonas! :–)

**Comment by j-hoff** [comment]
Hallo Jürgen, :)

I am pretty sure the description is part of the token view:
![eduMFA_token_view](https://github.com/eduMFA/eduMFA/assets/16492518/623af96d-f875-4536-84a2-38d8ce6c0a39)

So it might just be a configuration issue on your side or a misunderstanding, but get back to us if you suspect a bug.

Regarding the creation date, at the moment we are more focused on the API and passkeys than on a redesign of the web UI, but we might consider changes at a later point.

Closing this for now.

**Comment by ghost** [comment]
Indeed I suspect a misunderstanding and a resulting configuration issue. As we discussed this internally, the developer seemed to be unaware of the description field.  Thank you very much for the clarification!

We won't use eduMFA's web UI in production, rather an own web UI for end users that is much simpler and gives users more guidance through our process, now close to being finished for the first rollout. As a result of the the above, it doesn't have a description field at all. I hope we can change that later, but then I am not directly involved with the development work, just doing UI tests and evaluation.

Anyway, thanks again, and all the best!
