### ISSUE TITLE
Update from eduMFA 2.1.0 to eduMFA 2.2.0: edumfa-schema-upgrade not working

### ISSUE THREAD

**Issue by robert-roro** [eduMFA/eduMFA#238]
### Top-level intent

When updating from eduMFA 2.1.0 to eduMFA 2.2.0 the database schema upgrade with “edumfa-schema-upgrade /opt/edumfa/lib/edumfa/migrations” doesn’t work correctly for my setup:
```
(edumfa) $ /opt/edumfa/bin/edumfa-schema-upgrade /opt/edumfa/lib/edumfa/migrations
Can not import grpc modules.

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.2.0

++ Upgrading DB schema.
Can not import grpc modules.

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.2.0

Running online

```
```

SQL [edumfa]> select * from alembic_version;
+--------------+
| version_num  |
+--------------+
| 7d82d8b680a9 |
+--------------+
```
The new column “enforce_ma” has not been added to the table radiusserver.
When I login, a traceback is displayed in the logs:
```
_mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1054, "Unknown column 'radiusserver.enforce_ma' in 'field list'")
[SQL: SELECT radiusserver.id AS radiusserver_id, radiusserver.identifier AS radiusserver_identifier, radiusserver.server AS radiusserver_server, radiusserver.port AS radiusserver_port, radiusserver.secret AS radiusserver_secret, radiusserver.dictionary AS radiusserver_dictionary, radiusserver.description AS radiusserver_description, radiusserver.timeout AS radiusserver_timeout, radiusserver.retries AS radiusserver_retries, radiusserver.enforce_ma AS radiusserver_enforce_ma
FROM radiusserver]
```
I added the column to the table manually and then everything worked again.

### Steps to reproduce

1.	Updating eduMFA Version 2.1.0 to eduMFA Version 2.2.0
2.	Do the database migration manually. Database: Percona XtraDB Cluster (MySQL)

### Expected outcome

What do you think, how the system should have worked?

After edumfa-schema-upgrade the new column enforce_ma should have been created in the table radiusserver. 

### Actual outcome

What did actually happen?

edumfa-schema-upgrade runs without errors, but the column is not created.

### Configuration

* **eduMFA version**: 2.2.0
* **Installation method**:  github, pip3
* **Python version**: 3.10.12
* **Operating system**: Ubuntu Jammy Container with K0s
* **Webserver**: Kubernetes
* **Token database**: Percona XtraDB Cluster (MySQL)

### Log file

**Set EDUMFA_LOGLEVEL = logging.DEBUG in edumfa.cfg and take a look at the edumfa.log!**
**If appropriate, attach the log file or paste relevant portions.**

**Comment by fritterhoff** [comment]
Grr.... thats not good :( Would it be an option to manually reset the version to `0d011e94a8e8` and retry the upgrade with some additional arguments? I have to look it up but irrc there should be an option to get a little bit more output from the migrations.

**Comment by robert-roro** [comment]
Hello fritterhoff, thank you very much for your quick reply. Sure, if you send me the arguments, I can try it.

**Comment by fritterhoff** [comment]
Looks like I remembered it wrong. The `--sql` parameter doesn't work as I hoped. 

Unfortunately, I can't reproduce the error at the moment. 

The only option that comes to mind is that we edit the migration manually and add 1-2 log messages, reset the version and try to see if it occurs again.

**Comment by robert-roro** [comment]
If you tell me which log message/s I should add to which file.

**Comment by sklemer1** [comment]
The migration script is `migrations/versions/7d82d8b680a9_.py`. It seems that somehow this wasn't run, otherwise you would either had seen the message in line 23 or the column should be there. If we didn't screw up too much (or the alambic toolset) this could only happen if you didn't come from DB revision `0d011e94a8e8`. Anyway... this should be fairly easy to test:

If possible you might try the update again with the file above changed to

```
revision = '7d82d8b680a9'
down_revision = '0d011e94a8e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    print("Running Update to 7d82d8b680a9")
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        print("Adding enforce_ma column")
        op.add_column('radiusserver', sa.Column('enforce_ma', sa.Boolean(), nullable=True))
        print("Added enforce_ma column")
        # ### end Alembic commands ###
    except Exception as exx:
        print("Could not add column 'enforce_ma' in table radiusserver")
        print(exx)

    print('Update to 7d82d8b680a9 finished.')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radiusserver', 'enforce_ma')
    # ### end Alembic commands ###
```

**Comment by sklemer1** [comment]
Just to have mentioned it, but I'm pretty sure it doesn't apply here: In #212 we are investigating problems with special charactes in SQL DB passwords.

**Comment by robert-roro** [comment]
I mounted the new version of the migration file in the pod and checked the alembic version beforehand. Then I ran the edumfa-schema-upgrade again. It seems that the new migration is not executed at all, no logs appear that were inserted into the migration file. However, it is curious why the alembic version was upgraded afterwards or is it always upgraded on edumfa-schema-upgrade? EDUMFA_LOGLEVEL = logging.DEBUG

select * from alembic_version;

0d011e94a8e8

---

/opt/edumfa/lib/edumfa/migrations/versions/7d82d8b680a9_.py

```
revision = '7d82d8b680a9'
down_revision = '0d011e94a8e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    print("Running Update to 7d82d8b680a9")
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        print("Adding enforce_ma column")
        op.add_column('radiusserver', sa.Column('enforce_ma', sa.Boolean(), nullable=True))
        print("Added enforce_ma column")
        # ### end Alembic commands ###
    except Exception as exx:
        print("Could not add column 'enforce_ma' in table radiusserver")
        print(exx)

    print('Update to 7d82d8b680a9 finished.')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radiusserver', 'enforce_ma')
    # ### end Alembic commands ###

```
----

(edumfa) $ edumfa-schema-upgrade /opt/edumfa/lib/edumfa/migrations
Can not import grpc modules.

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.2.0

++ Upgrading DB schema.
Can not import grpc modules.
[2024-07-26 10:47:14,014][275][139654580736448][DEBUG][edumfa.app:234] Reading application from the static folder /opt/edumfa/lib/python3.10/site-packages/edumfa/static and the template folder static/templates/

               _       __  __ ______
              | |     |  \/  |  ____/\
       ___  __| |_   _| \  / | |__ /  \
      / _ \/ _` | | | | |\/| |  __/ /\ \
     |  __/ (_| | |_| | |  | | | / ____ \
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.2.0

Running online

----
select * from alembic_version;

7d82d8b680a9

----
@sklemer1: We ran into the problem when updating from 2.0.3. to 2.1.0. We have fixed it by changing the password.

**Comment by robert-roro** [comment]
Ohhh... damn. I caused the problem myself. I still had an old script in my container entry script. This prevented it from recognizing new migrations. The database migration works as it should. I am very sorry. I am closing this issue.

**Comment by fritterhoff** [comment]
Nevermind. Glad you found the bug.

**Comment by sklemer1** [comment]
Thanks for clarifying!
