### ISSUE TITLE
Remove authorization policy 'application_tokentype'

### ISSUE THREAD

**Issue by st-hofmann** [eduMFA/eduMFA#311]
The following policy must always be activated for fudiscr:

```
    {   'policy': [
          {
            'action': {
              'application_tokentype': True
            },
            'active': True,
            'name': 'idp-application-tokentype',
            'scope': 'authorization'
          }
       ]
    }
```

Why not activate this policy permanently? I also don't understand the need to ignore the token type for a request.

**Comment by fritterhoff** [comment]
Will implement as default.

**Comment by fritterhoff** [comment]
Since it is not possible to define a `false` policy to reject the tokentype I removed it completly and enabled it.

Right now the setting is stil displayed but has no effect anymore.
