### ISSUE TITLE
Adding ECDSA support for eduPUSH token

### ISSUE THREAD

**Issue by cristiano-palazzi** [eduMFA/eduMFA#327]
Hi, 

I'm developing a mobile authenticator that supports elliptic curve cryptography (P-256). I successfully enrolled an eduPush token, however, I encountered an issue during authentication.

The following line throws the error: TypeError: ECPublicKey.verify() takes 3 positional arguments but 4 were given
https://github.com/eduMFA/eduMFA/blob/c83b036984410fb46593c949195aff91e90192ae/edumfa/lib/tokens/pushtoken.py?plain=1#L735

It seems to fail because the `cryptography` module is attempting to verify an RSA signature using an elliptic public key, leading to the incorrect number of arguments being passed to the function.

Is ECDSA support planned for future releases?

**Comment by fritterhoff** [comment]
Hi,

From a quick view in the code I think it should be possible to catch the key type and add a `if-else` statement so we can handle the different signatures.

If you are familiar with Python feel free to create PR - otherwise I will check the options in the next weeks.

**Comment by fritterhoff** [comment]
@cristiano-palazzi I just created a simple fix for your problem. Feel free to test it and give us a short feedback.

**Comment by cristiano-palazzi** [comment]
@fritterhoff I tested the fix, and it works. I believe it's a good solution, as it can be adapted to other algorithms as well. Thanks for your help.
