### ISSUE TITLE
too long "Description" leads to ServerError 500 and unusable TOTP

### ISSUE THREAD

**Issue by bergerf** [eduMFA/eduMFA#330]
### Top-level intent

p(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(80)

### Steps to reproduce

1.  Enroll Token via WebUI
2. Choose TOTP
3. enter more than 80 characters into the Description field
4. press enroll

### Expected outcome

Cut off the Description input or limit the input field.
Do not create the TOTP.

### Actual outcome

"500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

The enrolled TOTP is not usable, there was no QR code. The TOTP is assigned to the user. There are no token-info keys.

### Configuration

* **eduMFA version**: 2.2.0
* **Installation method**: PyPI
* **Python version**: Python 3.11.2
* **Operating system**: Debian 12
* **Webserver**: Apache2
* **Token database**: PostgreSQL

### Log file

**Set EDUMFA_LOGLEVEL = logging.DEBUG in edumfa.cfg and take a look at the edumfa.log!**
**If appropriate, attach the log file or paste relevant portions.**
[edumfa.log](https://github.com/user-attachments/files/17145634/edumfa.log)

**Comment by fritterhoff** [comment]
Hi. Thanks for the report. Yes that seems to be a bug :) 

I think a limit in the UI should catch the most issues and in a second step we should handle that limitation in the backend and return e.g. a HTTP Status 400.

Will check that next week.
