### ISSUE TITLE
Dependency Flask-Versioned really required? It is from 2010...

### ISSUE THREAD

**Issue by johanneskastl** [eduMFA/eduMFA#334]
Hi,

is the Flask-Versioned dependency really necessary?

https://github.com/eduMFA/eduMFA/blob/main/requirements.txt#L62

```
flask-versioned==0.9.4.post20101221
```

I am asking because this is from 2010. The github repository does not look much better, no releases, last activity from 2015.

I know not all software needs to be updated, but 14 years is a lot...

Kind Regards,
Johannes

**Comment by fritterhoff** [comment]
Hi!

We also stumbled over this dependency and came to the conclusion that it is that simple that we will keep it right now. Prop. it is not really required... I will discuss it next week.

**Comment by fritterhoff** [comment]
Prop. to prevent caching -> Will remove and add `Cache-Control` header.

**Comment by fritterhoff** [comment]
Looks like the `Cache-Control` header gets already set to `no-cache`.

**Comment by johanneskastl** [comment]
Thanks for looking into this!
