### ISSUE TITLE
`edumfa-manage` backup with MariaDB Galera Cluster

### ISSUE THREAD

**Issue by gvde** [eduMFA/eduMFA#343]
### Top-level intent

When running `edumfa-manage backup create` I get an error:

```
mysqldump: Got error: 1235: "This version of MariaDB doesn't yet support 'LOCK TABLE on SEQUENCES in Galera cluster'" when using LOCK TABLES
```

### Steps to reproduce

1. Run eduMFA with a MariaDB Galera cluster as database
2. Run `edumfa-manage backup create` to backup

### Expected outcome

A successful backup.

### Actual outcome

```
Can not import grpc modules.

               _       __  __ ______      
              | |     |  \/  |  ____/\    
       ___  __| |_   _| \  / | |__ /  \   
      / _ \/ _` | | | | |\/| |  __/ /\ \  
     |  __/ (_| | |_| | |  | | | / ____ \ 
      \___|\__,_|\__,_|_|  |_|_|/_/    \_\       v2.2.0
    
mysqldump: Got error: 1235: "This version of MariaDB doesn't yet support 'LOCK TABLE on SEQUENCES in Galera cluster'" when using LOCK TABLES
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
```

### Configuration

* **eduMFA version**: 2.2.0
* **Installation method**: PyPi
* **Python version**: Python 3.9.18 (main, Aug 23 2024, 00:00:00)
* **Operating system**: AlmaLinux 9.4
* **Webserver**:
* **Token database**: mariadb-server-galera-10.5.22-1.el9_2.alma.1.x86_64

**Comment by fritterhoff** [comment]
Hi,

since the command only triggers a dump command (s. https://github.com/eduMFA/eduMFA/blob/main/edumfa/commands/manage/backup.py#L179-L190) does that work on a normal shell?

**Comment by gvde** [comment]
No. mariadb-dump doesn't work either.

```
(edumfa) [edumfa@idp9b-test ~]$ mariadb-dump --defaults-file=/etc/edumfa/mysql.cnf -h mdb.example.org -B edumfa -r /dev/null
mariadb-dump: Got error: 1235: "This version of MariaDB doesn't yet support 'LOCK TABLE on SEQUENCES in Galera cluster'" when using LOCK TABLES
```

I thought, it would just come down to a simple option to make mariadb-dump lock the whole database, but it seems that's not possible unless you have privileges to lock all databases and not only the edumfa database.

**Comment by fritterhoff** [comment]
I'm sorry but in this case we prop. have to rewrite the complete backup functionality or take the issue as it is 😞

**Comment by gvde** [comment]
After some more reading I think there is little you can do. The mariadb galera cluster doesn't support this at the moment, thus you cannot make a consistent (database locked) dump at the moment. It's only possible to lock all databases. Then it works. Of course, if you have multiple databases on the cluster this may cause problems.

Thus, the best you could probably do is to mention this issue when someone starts a backup.

Possible ways to proceed seem to be:

1. if the user has the RELOAD privilege, you can use `--lock-all-tables` if the user knows what it means to lock all tables in all database in the cluster for the duration of the dump
2. use `--single-transaction` instead to get a consistent dump. This seems to work only with InnoDB tables.
3. add `--skip-lock-tables` to dump without locks.

Either way, the user needs to know. You can only offer options to `edumfa-manage backup create` to select one of those options...

**Comment by pmainz** [comment]
I have added those three options to to `edumfa-manage backup create`.
It seams that mariadb is also working on a solution for this issue. So I guess we could think of reverting this commit once the issue is solved there.
