### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by Cornelicorn** [eduMFA/eduMFA#35]
### Top-level intent

Access the documentation

### Steps to reproduce

1. Visit https://edumfa.readthedocs.io/en/latest/installation/index.html as linked in the README

### Expected outcome

See the documentation

### Actual outcome

404 errors

**Comment by fritterhoff** [comment]
Yes we are aware of this bug and we are searching for the reason. Right now you can manually switch to the latest version.

**Comment by j-hoff** [comment]
seems ok now, no need to change the README :)
