### ISSUE TITLE
[Documentation] docker installation instructions should create config.cfg and make sure EDUMFA_LOGCONFIG is set.

### ISSUE THREAD

**Issue by kastl-ars** [eduMFA/eduMFA#359]
https://github.com/eduMFA/eduMFA/blob/3b367ec7b257dd3bfc9d6663a55adc22925dc3be/doc/installation/docker.rst?plain=1#L51

# Creation of the config file

The docker installation instructions should mention that the `config.cfg` should be created. A hint to [the documentation page](https://edumfa.readthedocs.io/en/v2.3.0/installation/system/inifile.html)  would be a good idea.

Side note: Why is the file called `config.cfg` and not `edumfa.cfg` like inside the container?

# EDUMFA_LOGCONFIG

Apparently the container image does not set `EDUMFA_LOGCONFIG`, which is also not included in the example configuration file.
There are errors when not specifying this, so this should be mentioned.

**Comment by fritterhoff** [comment]
Hi,

thanks for the hints. We will extend the docs.

**Comment by kastl-ars** [comment]
Thanks Florian!
