### ISSUE TITLE
edumfa-schema-upgrade: Unknown column 'policy.edumfanode' in 'field list'

### ISSUE THREAD

**Issue by charite-it-netz** [eduMFA/eduMFA#38]
I run ``edumfa-schema-upgrade eduMFA/migrations/`` and got this error message:

`
sqlalchemy.exc.OperationalError: (MySQLdb.OperationalError) (1054, "Unknown column 'policy.edumfanode' in 'field list'")
[SQL: SELECT policy.id AS policy_id, policy.active AS policy_active, policy.check_all_resolvers AS policy_check_all_resolvers, policy.name AS policy_name, policy.scope AS policy_scope, policy.action AS policy_action, policy.realm AS policy_realm, policy.adminrealm AS policy_adminrealm, policy.adminuser AS policy_adminuser, policy.resolver AS policy_resolver, policy.edumfanode AS policy_edumfanode, policy.user AS policy_user, policy.client AS policy_client, policy.time AS policy_time, policy.priority AS policy_priority, policycondition_1.id AS policycondition_1_id, policycondition_1.policy_id AS policycondition_1_policy_id, policycondition_1.section AS policycondition_1_section, policycondition_1.`Key` AS `policycondition_1_Key`, policycondition_1.comparator AS policycondition_1_comparator, policycondition_1.`Value` AS `policycondition_1_Value`, policycondition_1.active AS policycondition_1_active 
FROM policy LEFT OUTER JOIN policycondition AS policycondition_1 ON policy.id = policycondition_1.policy_id ORDER BY policycondition_1.id]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
`

**Comment by fritterhoff** [comment]
Hi,

do you maybe have a bit more output? In case of a broken migration the schema-upgrade it should output a little bit more output which step is failing...

**Comment by ikreb7** [comment]
I added more logs to #39  and close this issue again.
