### ISSUE TITLE
SQLIdResolver causes eduMFA to crash

### ISSUE THREAD

**Issue by Glokeru** [eduMFA/eduMFA#440]
### Top-level intent

I am from the Friedrich-Alexander-University Erlangen Nürnberg. We used PrivacyIDEA for about 2 years now, had no support from Netknights and everything worked fine. One week ago we migrated PrivacyIDEA to eduMFA. The migration process had no issues.  Since we integrated PrivacyIDEA in our IdM System, we dont use the WebUI for any user interaction, everything works with the provided API. For resolving the users we use the an SQL-Resolver with MariaDB 10.11. The user table is in the same database as eduMFA. The database runs on the localhost. After the migration we are experiencing dissapearing users when running the WSGI-App with more than one Apache process or multiple threads. To get the users back an Apache restart is needed.  I could reproduce this issue on our test system that has a own database and only a few manual added users.

 
### Steps to reproduce

1.  Install edumfa and edumfa-apache2  Ubuntu packages
2.  Install mariadb-server provided by Ubuntu
3.  Create a realm with an SQL-Resolver in editable mode
4.  Login as admin and add some users (maybe one is enough)
6.  Open one user and click refresh multiple times
7.  After some refreshes an ERR904 will occur and no other users in the resolver will be found
8.  The users tab will show 0 users in the resolver and eduMFA logs this error:
`[ERROR][edumfa.lib.user:744] OperationalError("(pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')")`
`[ERROR][edumfa.lib.user:744] PendingRollbackError("Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding")`
`[ERROR][edumfa.lib.resolvers.SQLIdResolver:347] Could not get the user ID: PendingRollbackError("Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding")`
9.  At this point an Apache restart is necessary to find the users again
10.  Workaround: Start WSGI with one process and one thread then everything works fine
`WSGIDaemonProcess edumfa processes=1 threads=1 display-name=%{GROUP} user=edumfa`
11. We tried other db-drivers than pymysql with the same result
12. PrivacyIDEA worked fine with the same setup

### Expected outcome

eduMFA should not loose all users in the SQL-Resolver, with an Ldap-Resolver everything works fine.

### Actual outcome

eduMFA needed an Apache restart to find the users from the SQL-Resolver again.

### Configuration

* **eduMFA version**: 2.3.0 
* **Installation method**:  Ubuntu packages
* **Python version**:  as provided by the venv: 3.12
* **Operating system**: Ubuntu 24.04
* **Webserver**: Apache
* **Token database**: MariaDB 10.11
 
### Log file

...attached
[edumfa.log](https://github.com/user-attachments/files/17920518/edumfa.log)

If any further information is needed to reproduce the issue dont hesitate to contact me.

**Comment by fritterhoff** [comment]
Hi, 

since you write that it occurred with multiple processes/threads I would assume that we run in a strange multiprocessing bug. 

From my very first check the usage of the session objects I maybe already found a bug ... do you maybe have some time for a short zoom/... that we can debug it together?

Thanks!
Flo
