### ISSUE TITLE
Packaging eduMFA for openSUSE: What is the minimum/maximum python version?

### ISSUE THREAD

**Issue by kastl-ars** [eduMFA/eduMFA#463]
Dear maintainers,

I am trying to package eduMFA for openSUSE. I came across the python version constraints and was wondering, which one is correct:

```
eduMFA currently runs with Python 3.6 to 3.10.
```
https://edumfa.readthedocs.io/en/latest/installation/pip.html

```
requires-python = ">=3.8"
```
https://github.com/eduMFA/eduMFA/blob/main/pyproject.toml#L8

The reason I am asking is because the main python stack in openSUSE Leap is 3.11 (as 3.6 is EOL), which openSUSE Tumbleweed/MicroOS/... are using multiple python versions. Currently python3.10 is the lowest, but will be dropped now that python3.13, 3.12 and 3.11 are supported. python3.11 is the "default", but will be switched to 3.12 soon.

I take it that 3.8 is the minimum version and the docs are outdated in that regard?

What about the upper limit?

Kind Regards,
Johannes

**Comment by fritterhoff** [comment]
The docs are wrong. Minimum right now is 3.8 max. is 3.12 but we will drop 3.8 and add 3.13 with one of the next releases.

**Comment by kastl-ars** [comment]
Thanks for the fast confirmation, Florian!
